// apps/ai-assistant/src/content-scripts/index.tsx
import { createShadowRootUI } from '@webx-kit/runtime/content-scripts';
import { createRoot } from 'react-dom/client';
import { App } from './app';
import './global.less';

createShadowRootUI({
  styles: chrome.runtime.getURL('static/css/content-script.css'),
  render({ root }) {
    createRoot(root).render(<App />);
  },
});

// templates/solid/src/content-scripts/index.tsx
import { createShadowRootUI } from '@webx-kit/runtime/content-scripts';
import { render } from 'solid-js/web';
import { App } from './app';
import '../global.less';

createShadowRootUI({
  styles: chrome.runtime.getURL('static/css/content-script.css'),
  render({ root }) {
    render(() => <App />, root);
  },
});
